export const models = {
    config: {
        ConfigID: 'TEXT PRIMARY KEY NOT NULL',
        Serial: 'TEXT',
        AppVersion: 'TEXT',
        LastSync: 'INTEGER NOT NULL',
        Token: 'TEXT',
        Organisation: 'TEXT',
        LastServerSync: 'INTEGER NOT NULL',
        CreatedDateUTC: 'INTEGER NOT NULL',
        UpdatedDateUTC: 'INTEGER NOT NULL',
        DeletedDateUTC: 'INTEGER NOT NULL',
        ServerDateUTC: 'INTEGER NOT NULL',

    },
    employee: {
        EmployeeID: 'TEXT PRIMARY KEY NOT NULL',
        Firstname: 'TEXT NOT NULL',
        Surname: 'TEXT NOT NULL',
        Rfid: 'TEXT',
        RfidCode: 'TEXT',
        Termdate: 'TEXT',
        Supervisor: 'INTEGER NOT NULL',
        CreatedDateUTC: 'INTEGER NOT NULL',
        UpdatedDateUTC: 'INTEGER NOT NULL',
        DeletedDateUTC: 'INTEGER NOT NULL',
        ServerDateUTC: 'INTEGER NOT NULL',
    },
    weight: {
        TransactionID: 'TEXT PRIMARY KEY',
        Weight: 'INTEGER NOT NULL',
        EmployeeID: 'TEXT NOT NULL',
        SupervisorID: 'TEXT',
        FieldID: 'TEXT NOT NULL',
        VarietyID: 'TEXT',
        AssetID: 'TEXT',
        SerialNumber: 'TEXT',
        CreatedDateUTC: 'INTEGER NOT NULL',
        UpdatedDateUTC: 'INTEGER NOT NULL',
        DeletedDateUTC: 'INTEGER NOT NULL',
        ServerDateUTC: 'INTEGER NOT NULL',
    },
    field: {
        AreaID: 'TEXT PRIMARY KEY',
        Title: 'TEXT NOT NULL',
        Description: 'TEXT NOT NULL',
        Variety: 'TEXT NOT NULL',
        VarietyID: 'TEXT NOT NULL',
        CreatedDateUTC: 'INTEGER NOT NULL',
        UpdatedDateUTC: 'INTEGER NOT NULL',
        DeletedDateUTC: 'INTEGER NOT NULL',
        ServerDateUTC: 'INTEGER NOT NULL',
    },
    asset: {
        AssetID: 'TEXT PRIMARY KEY',
        OrganisationID: 'TEXT NOT NULL',
        AssetNumber: 'TEXT NOT NULL',
        AssetDescription: 'TEXT NOT NULL',
        AssetType: 'TEXT NOT NULL',
        RFID: 'TEXT NOT NULL',
        RFIDCode: 'TEXT NOT NULL',
        CreatedDateUTC: 'INTEGER NOT NULL',
        UpdatedDateUTC: 'INTEGER NOT NULL',
        DeletedDateUTC: 'INTEGER NOT NULL',
        ServerDateUTC: 'INTEGER NOT NULL',
    },
    operation: {
        OperationID: 'TEXT PRIMARY KEY',
        OperationCode: 'TEXT NOT NULL',
        Description: 'TEXT NOT NULL',
        CreatedDateUTC: 'INTEGER NOT NULL',
        UpdatedDateUTC: 'INTEGER NOT NULL',
        DeletedDateUTC: 'INTEGER NOT NULL',
        ServerDateUTC: 'INTEGER NOT NULL',
    },
    device: {
        serial: 'TEXT PRIMARY KEY',
        ip: 'TEXT NOT NULL',
        port: 'TEXT NOT NULL',
        username: 'TEXT NOT NULL',
        password: 'TEXT NOT NULL',
        lastUsed: 'INTEGER',
    },
}